#!/bin/bash
BLACK='\e[0;30m'
BLUE='\e[0;34m'
GREEN='\e[0;32m'
CYAN='\e[0;36m'
RED='\e[0;31m'
PURPLE='\e[0;35m'
BROWN='\e[0;33m'
LIGHTGRAY='\e[0;37m'
DARKGRAY='\e[1;30m'
LIGHTBLUE='\e[1;34m'
LIGHTGREEN='\e[1;32m'
LIGHTCYAN='\e[1;36m'
LIGHTRED='\e[1;31m'
LIGHTPURPLE='\e[1;35m'
YELLOW='\e[1;33m'
WHITE='\e[1;37m'
NC='\e[0m'              # No Color
clear
echo -e "${GREEN}"
echo "+===============================+"
echo "+-------------------------------+"
echo "+    ___  _               _     +"  
echo "+   | . || |_  ___  _ _ _| |_   +" 
echo "+   |   || . \/ . \| | | | |    +"  
echo "+   |_|_||___/\___/|___| |_|    +"
echo "+-------------------------------+"
echo "+===============================+"
echo -e "${LIGHTBLUE}[Nombre Del Proyecto] ${BLUE}zTreme     "
echo -e "${LIGHTBLUE}[Version] ${GREEN}    zTreme Version 1.0     "
echo -e "${LIGHTBLUE}[Fecha De Creación] ${RED} 11-7-11     "
echo -e "${LIGHTBLUE}[Tamaño] ${RED}         ~201KB    "
echo -e " "
echo -e "${LIGHTBLUE}[Developed By] ${RED} zStat1cHack#3525    "
echo -e "${LIGHTBLUE}[Coder] ${RED}        zStat1cHack#3525   "
echo -e "${LIGHTBLUE}[Beta Tester] ${RED}  Law#8879   "
echo -e ""
echo -e "${LIGHTBLUE}[IMPORTANTE] "
echo -e "${RED}"
echo -e "No asumimos ninguna responsabilidad por lo que utilice esta herramienta para lograr."
echo -e "Esta herramienta está diseñada para uso privado / personal para realizar pruebas de estrés en" 
echo -e "Equipo de red. Puede ser ilegal utilizar este software para otros fines."
echo -e "que su uso previsto"
echo -e ""
echo -e "NO REDISTRIBUIR NI ALTERAR zTreme!"
read

